P8105 - Homework 3
================
Mingkuan Xu

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

    ## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
    ## ✓ tibble  3.1.4     ✓ dplyr   1.0.7
    ## ✓ tidyr   1.1.3     ✓ stringr 1.4.0
    ## ✓ readr   2.0.1     ✓ forcats 0.5.1

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(p8105.datasets)
```

## Problem 1

#### Part 1 - Data import & description

``` r
data("instacart")
head(instacart)
```

    ## # A tibble: 6 × 15
    ##   order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##      <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ## 1        1      49302                 1         1  112108 train               4
    ## 2        1      11109                 2         1  112108 train               4
    ## 3        1      10246                 3         0  112108 train               4
    ## 4        1      49683                 4         0  112108 train               4
    ## 5        1      43633                 5         1  112108 train               4
    ## 6        1      13176                 6         0  112108 train               4
    ## # … with 8 more variables: order_dow <int>, order_hour_of_day <int>,
    ## #   days_since_prior_order <int>, product_name <chr>, aisle_id <int>,
    ## #   department_id <int>, aisle <chr>, department <chr>

This is an anonymized dataset recording online grocery orders from
Instacart users. Each row in the dataset is a product from an order;
there is a single order per user in this dataset. There are 1384617
total rows in this dataset with 15 columns, recording 131209 orders in
total. The recorded information include: order id, product id, add to
cart order, reordered, user id, eval set, order number, order dow, order
hour of day, days since prior order, product name, aisle id, department
id, aisle, department. There are some interesting observations of this
dataset. For example, there are 21 departments in total, including dairy
eggs, produce, canned goods, beverages, deli, snacks, pantry, frozen,
meat seafood, household, bakery, personal care, dry goods pasta, babies,
missing, other, breakfast, international, alcohol, bulk, pets.

#### Part 2 - Analysis of aisles

``` r
instacart %>% pull(aisle) %>% unique() %>% length() # Find number of aisles.
```

    ## [1] 134

``` r
instacart_by_aisle = 
  instacart %>% 
  count(aisle) %>% 
  arrange(desc(n)) 

head(instacart_by_aisle,1)# Find most popular aisle
```

    ## # A tibble: 1 × 2
    ##   aisle                 n
    ##   <chr>             <int>
    ## 1 fresh vegetables 150609

Using the codes above, we found that there are 134 aisles in total, with
aisle of the fresh vegetables being the most popular one from which
150609 items were ordered.

#### Part 3 - Plot of items from aisles.

Now we plot the number of items ordered in each aisle, limiting this to
aisles with more than 10000 items ordered using the following code.

``` r
instacart_by_aisle %>% 
  filter(n>10000)  %>%
  ggplot(.,aes(x=reorder(aisle,n),y=n)) + 
  geom_bar(stat="identity") +
  xlab("Aisle")+
  ylab("Number of Items") +
  coord_flip()
```

![](p8105_hw3_mx2262_files/figure-gfm/p1_part3-1.png)<!-- -->

#### Part 4 - Three most popular items

Using the code below, we display the table showing the three most
popular items in each of the aisles “baking ingredients”, “dog food
care”, and “packaged vegetables fruits”.

``` r
baking_ingredients = 
  instacart %>%
  filter(aisle=="baking ingredients") %>%
  count(product_name) %>%
  arrange(desc(n)) %>%
  mutate(Aisle="Baking Ingredients") %>%
  rename(Product=product_name,Count=n)%>%
  relocate(Aisle) %>%
  head(3)
  

dog_food_care = 
  instacart %>%
  filter(aisle=="dog food care") %>%
  count(product_name) %>%
  arrange(desc(n)) %>%
  mutate(Aisle="Dog Food Care") %>%
  rename(Product=product_name,Count=n)%>%
  relocate(Aisle) %>%
  head(3)

packaged_vegetables_fruits = 
  instacart %>%
  filter(aisle=="packaged vegetables fruits") %>%
  count(product_name) %>%
  arrange(desc(n)) %>%
  mutate(Aisle="Packaged Vegetables Fruits") %>%
  rename(Product=product_name,Count=n)%>%
  relocate(Aisle) %>%
  head(3)

popular_table = 
  bind_rows(baking_ingredients,
                          dog_food_care,
                          packaged_vegetables_fruits) %>%
  arrange(desc(Count))

popular_table %>% knitr::kable(digits = 1)
```

| Aisle                      | Product                                       | Count |
|:---------------------------|:----------------------------------------------|------:|
| Packaged Vegetables Fruits | Organic Baby Spinach                          |  9784 |
| Packaged Vegetables Fruits | Organic Raspberries                           |  5546 |
| Packaged Vegetables Fruits | Organic Blueberries                           |  4966 |
| Baking Ingredients         | Light Brown Sugar                             |   499 |
| Baking Ingredients         | Pure Baking Soda                              |   387 |
| Baking Ingredients         | Cane Sugar                                    |   336 |
| Dog Food Care              | Snack Sticks Chicken & Rice Recipe Dog Treats |    30 |
| Dog Food Care              | Organix Chicken & Brown Rice Recipe           |    28 |
| Dog Food Care              | Small Dog Biscuits                            |    26 |

#### Part 5 - The mean hour of the day

Using the codes below, we display the table showing the mean hour of the
day at which Pink Lady Apples and Coffee Ice Cream are ordered, from
Sunday to Saturday.

``` r
pink_lady_apples = 
  instacart %>%
  filter(product_name == "Pink Lady Apples") %>%
  select(order_dow,order_hour_of_day) %>%
  group_by(order_dow) %>%
  summarize(
    median_hour_of_day = mean(order_hour_of_day)
  ) %>%
  rename("Pink Lady Apples"=median_hour_of_day)


coffee_ice_cream = 
  instacart %>%
  filter(product_name == "Coffee Ice Cream") %>%
  select(order_dow,order_hour_of_day) %>%
  group_by(order_dow) %>%
  summarize(
    median_hour_of_day = mean(order_hour_of_day)
  ) %>%
  rename("Coffee Ice Cream"=median_hour_of_day)

median_hour_table = 
  left_join(pink_lady_apples,coffee_ice_cream,by="order_dow") %>%
  select(-order_dow)
# mutate("Day of Week" = c("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"))

median_hour_table %>% knitr::kable(digits = 1)
```

| Pink Lady Apples | Coffee Ice Cream |
|-----------------:|-----------------:|
|             13.4 |             13.8 |
|             11.4 |             14.3 |
|             11.7 |             15.4 |
|             14.2 |             15.3 |
|             11.6 |             15.2 |
|             12.8 |             12.3 |
|             11.9 |             13.8 |

## Problem 2

#### Part 1 - Data preprocessing

We start by using the following codes to tide up the dataset.

``` r
data("brfss_smart2010")

data_brfss = brfss_smart2010 %>%
  janitor::clean_names() %>% 
  filter(topic=="Overall Health") %>%
  filter(response %in% c("Excellent","Very good","Good","Fair","Poor")) %>%
  mutate(response = factor(response,levels = c("Poor","Fair","Good","Very good","Excellent")))

head(data_brfss) 
```

    ## # A tibble: 6 × 23
    ##    year locationabbr locationdesc  class  topic  question   response sample_size
    ##   <int> <chr>        <chr>         <chr>  <chr>  <chr>      <fct>          <int>
    ## 1  2010 AL           AL - Jeffers… Healt… Overa… How is yo… Excelle…          94
    ## 2  2010 AL           AL - Jeffers… Healt… Overa… How is yo… Very go…         148
    ## 3  2010 AL           AL - Jeffers… Healt… Overa… How is yo… Good             208
    ## 4  2010 AL           AL - Jeffers… Healt… Overa… How is yo… Fair             107
    ## 5  2010 AL           AL - Jeffers… Healt… Overa… How is yo… Poor              45
    ## 6  2010 AL           AL - Mobile … Healt… Overa… How is yo… Excelle…          91
    ## # … with 15 more variables: data_value <dbl>, confidence_limit_low <dbl>,
    ## #   confidence_limit_high <dbl>, display_order <int>, data_value_unit <chr>,
    ## #   data_value_type <chr>, data_value_footnote_symbol <chr>,
    ## #   data_value_footnote <chr>, data_source <chr>, class_id <chr>,
    ## #   topic_id <chr>, location_id <chr>, question_id <chr>, respid <chr>,
    ## #   geo_location <chr>

#### Part 2 - Which states were observed at 7 or more locations?

``` r
data_brfss_2002 = 
  data_brfss %>%
  filter(year==2002) %>%
  select(locationabbr,locationdesc) %>%
  distinct() %>%
  count(locationabbr) %>%
  filter(n>=7)

data_brfss_2010 = 
  data_brfss %>%
  filter(year==2010) %>%
  select(locationabbr,locationdesc) %>%
  distinct() %>%
  count(locationabbr) %>%
  filter(n>=7)
```

We use the above code o find out which states were observed at 7 or more
locations in 2002 and 2010. In conclusion, in 2002, the abbreviated
names of those states are CT, FL, MA, NC, NJ, PA; in 2010, those states
are CA, CO, FL, MA, MD, NC, NE, NJ, NY, OH, PA, SC, TX, WA. We observed
significantly more locations recorded in 2010 compared with 2002.

#### Part 3 - The “spaghetti” plot

``` r
data_brfss_excellent = 
  data_brfss %>%
  filter(response=="Excellent") %>%
  drop_na(data_value) %>%
  group_by(year,locationabbr) %>%
  summarize(
    mean_value = mean(data_value)
  ) 
```

    ## `summarise()` has grouped output by 'year'. You can override using the `.groups` argument.

``` r
ggplot(data_brfss_excellent,aes(x=year,y=mean_value,color=locationabbr)) + 
  geom_line() +
  geom_point() +
  labs(
    title = "The “Spaghetti” Plot of Excellent Responses (2002~2010)",
    color = "States") +
  ylab("Mean Value")+
  xlab("Year")+
  theme_classic()
```

![](p8105_hw3_mx2262_files/figure-gfm/p2_part3-1.png)<!-- -->

#### Part 4 - The two-panel plot of NY

``` r
data_ny_2006_2010 = 
  data_brfss %>%
  filter(year %in% c(2006,2010),locationabbr=="NY") %>%
  select(year,locationdesc,data_value,response) %>%
  drop_na(data_value)

data_ny_2006_2010 %>%
  ggplot(aes(x=locationdesc,y=data_value)) + 
  geom_bar(aes(fill=response),stat="identity") +
  facet_grid(. ~ year) + 
  coord_flip() +
  theme(legend.position = "bottom") +
  xlab("Data Values")+
  ylab("Locations")+
  labs(title = "A Two-Panel Plot of Responses in NY (2006 vs 2010)")+
  theme_classic()
```

![](p8105_hw3_mx2262_files/figure-gfm/p2_part4-1.png)<!-- -->
